language: cpp
os: linux
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - valgrind
      - cppcheck


script:
  # скрипт сборки и тестирования проекта:
#  - cmake -DCMAKE_CXX_COMPILER="g++-6" ..
#  - make
#  - ctest -T memcheck
  - mkdir build
  - cd build
  - cmake ../ -DCMAKE_BUILD_TYPE=Debug -DTARGET_CPU=x86
  - cmake --build . --target Tests
#  - valgrind --tool=memcheck --gen-suppressions=all --leak-check=full --track-origins=yes --vgdb=no ./project/tests/Tests
#  - cppcheck ../project/src
#  - cppcheck ../project/tests/test.cpp
#  - cppcheck ../project/main.c | ls -la